summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-12.0-x86_64/releases/download/2024.06.01/pkg-config-0.29.2-macos-12.0-x86_64.tar.xz
bin-sha: 013a9d02ddd1e25136c408b48ab00d48bfd8d254df9962b1734f5d08d21d03ec
